display:
  name: "User Portal V1"
server:
  port: 7070  
  
database:
  name: user_portal
  username: root
  password: root
  url: jdbc:mysql://localhost:3306/user_portal
 # driverClassName: com.mysql.jdbc.Driver
  connectionTimeout: 10000
  minimumIdle: 2
  maximumPoolSize: 5
  idleTimeout: 200000
  maxLifeTimeout: 600000
  
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/user_portal
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true    
  
userPortal:
  login:
    path: /login
  registration:
    path: /registration
  user-management:
    path: /userManagement
